spring.application.name=docker-audit-api
server.port=${SERVER_PORT:8080}

spring.datasource.url=${APP_POSTGRES_URL:jdbc:postgresql://localhost:5432/audit_db}
spring.datasource.username=${APP_POSTGRES_USER:audit_user}
spring.datasource.password=${APP_POSTGRES_PASSWORD:secure_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

app.clickhouse.url=${APP_CLICKHOUSE_URL:jdbc:clickhouse://localhost:8123/audit_analytics}
app.clickhouse.username=${APP_CLICKHOUSE_USER:audit_user}
app.clickhouse.password=${APP_CLICKHOUSE_PASSWORD:secure_password}
app.clickhouse.driver-class-name=${APP_CLICKHOUSE_DRIVER:com.clickhouse.jdbc.ClickHouseDriver}

app.security.jwt.issuer=${APP_JWT_ISSUER:docker-audit-api}
app.security.jwt.secret=${APP_JWT_SECRET:change-me-in-prod-please-change-me-in-prod-1234567890}
app.security.jwt.ttl=${APP_JWT_TTL:PT24H}
